name: retailflow-etl

services:
  postgres:
    image: postgres:16-alpine
    container_name: retail-postgres
    environment:
      POSTGRES_DB: retail_dw
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
    ports:
      - "5432:5432"
    volumes:
      - retail_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_user -d retail_dw"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  retail_postgres_data:

